var SCREEN_WIDTH = 1024;
var SCREEN_HEIGHT = 576;

var SAND_Y = SCREEN_HEIGHT - 80;

var GRAVITY = 990;

var NUM_TOURISTS = 3;
var TOURIST_SPEED = 100;

var CLOUD_SPEED = 40;

var BAR_MS = 800;
var TREE_ATTACKS_PER_BAR = 2;

var MAX_RUBBISH = 50;

var TEXT_X_SCALE = 1.5;

var TREE_BOUNCE = 0.25;
var TREE_ROTATE = 25;
